### ISSUE TITLE
Jobs external url

### ISSUE THREAD

**Issue by benoitfrisch** [AcelLuxembourg/AcelLu#1]
On the page https://acel.lu/inform/jobs, the url to zap.lu leads to an internal error 404.

I think, it would be good to catch such errors generated by bad user handling of the field, or some other reason.

I would suggest to adjust AcelJob/src/AcelJob/Entity/Job.php externalUrl Getter, and check if "http://" exists, and if not, add it manually, to prevent the 404 errors.

Examples:
-[https://acel.lu/inform/www.zap.lu](https://acel.lu/inform/www.zap.lu)
-[https://acel.lu/inform/www.cdclux.com](https://acel.lu/inform/www.cdclux.com)

Would it be possible that you provide short set up instructions in ReadMe for contributors? 
This would make it easier to test own fixes for something like that and simply create a pull request. It think that this should be the goal of an open source website. :)

**Comment by mirkomack** [comment]
Hi @benoitfrisch,

thanks for your advise. You are right, that there was a problem. I updated the JobsForm and CompanyForm so that no "wrong" urls will get in the database. I think it is better to tackle the problem at the root than to handle wrong urls.

You are right with your opinion about the readme, I will update it in the next weeks.
